name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies for Functions
        run: npm install
        working-directory: ./functions
      - name: Build Functions
        run: npm run build
        working-directory: ./functions
      - name: Install Dependencies for AngularApp
        run: export NG_CLI_ANALYTICS=ci && npm install
        working-directory: ./ngapp
      - name: Build AngularApp
        run: npm run build
        working-directory: ./ngapp
      - name: Deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  