name: Update Static Website
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
        
jobs:
  build:
    name: UpdateStatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Data
        run: curl https://myrke-189201.firebaseio.com/posts.json > posts.json
  