name: UpdateStatic

on: 
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v1.0.0
        required: false

jobs:
  build:
    name: UpdateStatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Decrypt firebase admin json
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.GPG_PASS }}" --output staticupdater/firebase-adminsdk.json firebase-adminsdk.json.gpg

