name: UpdateStatic

on: 
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v1.0.0
        required: false

jobs:
  build:
    name: UpdateStatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Srv account file
        run: 'echo ${{ secrets.FIREBASE_SRVACC }} > staticupdater/src/srvacc.json'
      - name: Test Srv acc file
        run: 'echo staticupdater/src/srvacc.json | grep project_id'
