name: UpdateStatic

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v1.0.0
        required: false

jobs:
  build:
    name: UpdateStatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Decrypt firebase admin json
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.GPG_PASS }}" --output staticupdater/firebase-adminsdk.json staticupdater/firebase-adminsdk.json.gpg
      - name: Build StaticUpdater
        run: npm i && npm run build
        working-directory: ./staticupdater
      - name: Run StaticUpdater
        run: npm run start
        working-directory: ./staticupdater
      - name: Deploy Static WebApp
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:static
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

