name: Update Static Website

jobs:
  build:
    name: UpdateStatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Data
        run: curl https://myrke-189201.firebaseio.com/posts.json > posts.json
  